### ISSUE TITLE
Feature Request - Generic API

### ISSUE THREAD

**Issue by rpruden** [simontelephonics/smsconnector#50]
Would it be possible to create a "Generic" integration that allows you to specify the inbound and outbound URLs.

Secondarily, we have worked with a platform called Textable that is integrated with Flowroute. I'm thinking it would be great to have the messages arrive in Textable, and then forward on to this API endpoint and then to send return responses to Textable's API endpoint so that communications would show up in the Textable App and the Sangoma App.

**Comment by billsimon** [comment]
SMS Connector essentially is a "generic API" in that you can write a module for any REST-style SMS provider. But we cannot make it more generic just by specifying inbound/outbound URLs because there is no generic standard. 

A provider module could be written for Textable if it has a REST API; please open a feature request for that.
