### ISSUE TITLE
Tampered Files

### ISSUE THREAD

**Issue by Dagnabit99** [simontelephonics/smsconnector#60]
How can I get around the module showing up as "Tampered" on the FreePBX dashboard? 

You have 2 tampered files
Module "SMS Connector" signed by an invalid key.
Module: "SMS Connector", File: "module.sig check failed! Signed by unknown, untrusted key."

It's not all that important... mostly aesthetics. Does FreePBX have a way to self-sign?

**Comment by billsimon** [comment]
It is signed. Check the signature by going into Module Admin. 

![image](https://github.com/user-attachments/assets/f450fb3c-d501-47a7-b8e3-fb47fbe31c10)

Just clear the warning from the dashboard and it should not come back again. I think this sometimes happens because FreePBX reloads and checks the module signatures before the key is fetched from the opengpg directory.
